# Here defines the parameters for each algorithm and dataset.
# These parameters are not the same as the parameters used in the paper
parameterMap = {
    "LfF": {
        "house_price": {  # 默认参数 不想每列都写的就改默认值
            "l2_regularizer_weight": 0.001,
            "irm_type": "lff",
            "dataset": "house_price",
            "n_restarts": 1,
            "seed": 1,
            "hidden_dim_infer": 64,
            "hidden_dim": 32,
            "lr": 0.00005,
            "penalty_anneal_iters": 2000,
            "steps":1,
        },
        "celebaz_feature": {  # 默认参数 不想每列都写的就改默认值
            "l2_regularizer_weight": 0.001,
            "noise_ratio": 0.2,
            "cons_train": "0.999_0.8",
            "cons_test": "0.01_0.2_0.8_0.999",
            "penalty_weight": 2000,
            "dim_inv": 5,
            "dim_sp": 5,
            "data_num_train": 39996,
            "data_num_test": 20000,
            "dataset": "celebaz_feature",
            "n_restarts": 1,
            "seed": 1,
            "irm_type": "lff",
            "lr": 0.0001,
            "penalty_anneal_iters": 2000,
            "steps":1,
        },
        "logit_z": {
            "l2_regularizer_weight": 0.002,
            "noise_ratio": 0.1,
            "cons_train": "0.999_0.9",
            "cons_test": "0.999_0.8_0.2_0.001",
            "penalty_weight": 2000,
            "dim_inv": 5,
            "dim_sp": 10,
            "data_num_train": 5000,
            "data_num_test": 5000,
            "dataset": "logit_z",
            "n_restarts": 1,
            "seed": 1,
            "irm_type": "lff",
            "lr": 0.0005,
            "penalty_anneal_iters": 2000,
            "steps":1,
        },
        "landcover": {
            "aux_num": "2",
            "batch_size": "1024",
            "seed": "112",
            "classes_num": "6",
            "dataset": "landcover",
            "opt": "adam",
            "l2_regularizer_weight": 0.001,
            "n_restarts": "1",
            "num_classes": "6",
            "z_class_num": "2",
            "penalty_weight": "2",
            "n_restarts": 1,
            "irm_type": "lff",
            "lr": 0.08,
            "steps":1,
            "penalty_anneal_iters": 50,
            "scheduler": 1,
        },
    },
    "EIIL": {
        "house_price": {  # 默认参数 不想每列都写的就改默认值
            "l2_regularizer_weight": 0.001,
            "irm_type": "eiil",
            "dataset": "house_price",
            "n_restarts": 1,
            "seed": 1,
            "hidden_dim_infer": 64,
            "hidden_dim": 32,
            "lr": 0.004,
            "penalty_anneal_iters": 2000,
            "steps":1,
        },
        "celebaz_feature": {  # 默认参数 不想每列都写的就改默认值
            "l2_regularizer_weight": 0.001,
            "noise_ratio": 0.2,
            "cons_train": "0.999_0.8",
            "cons_test": "0.01_0.2_0.8_0.999",
            "penalty_weight": 2000,
            "dim_inv": 5,
            "dim_sp": 5,
            "data_num_train": 39996,
            "data_num_test": 20000,
            "dataset": "celebaz_feature",
            "n_restarts": 1,
            "seed": 1,
            "irm_type": "eiil",
            "lr": 0.0001,
            "penalty_anneal_iters": 2000,
            "steps":1,
        },
        "logit_z": {
            "l2_regularizer_weight": 0.002,
            "noise_ratio": 0.1,
            "cons_train": "0.999_0.9",
            "cons_test": "0.999_0.8_0.2_0.001",
            "penalty_weight": 2000,
            "dim_inv": 5,
            "dim_sp": 10,
            "data_num_train": 5000,
            "data_num_test": 5000,
            "dataset": "logit_z",
            "n_restarts": 1,
            "seed": 1,
            "irm_type": "eiil",
            "lr": 0.005,
            "penalty_anneal_iters": 2000,
            "steps":1,
        },
        "landcover": {
            "aux_num": "2",
            "batch_size": "1024",
            "seed": "112",
            "classes_num": "6",
            "dataset": "landcover",
            "opt": "adam",
            "l2_regularizer_weight": 0.001,
            "n_restarts": "1",
            "num_classes": "6",
            "z_class_num": "2",
            "penalty_weight": "2",
            "n_restarts": 1,
            "irm_type": "eiil",
            "lr": 0.08,
            "steps":1,
            "penalty_anneal_iters": 50,
            "scheduler": 1,
        },
    },
    
    
}
